name: liff_calendar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_line_liff: ^0.0.3
  table_calendar: ^3.0.8
  gsheets: ^0.4.2
  freezed_annotation: ^2.2.0
  json_serializable: ^6.5.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.3.2
  freezed: ^2.2.1

flutter: 
  uses-material-design: true

